#!/bin/bash

# Shopware DDEV Installer
# Autor: Andreas van Hulst
# Lizenz MIT

BOLD="\033[1m"
GRAY="\033[2;37m"
NC="\033[0m"

DATA=`wget -cq https://update-api.shopware.com/v1/releases/install -O - | jq '.'`

function help() {
	echo -e "Usage: ${BOLD}install <version> | versions${NC}"
	echo -e "install verwendet die aktuelle Verion"
	echo -e "install 5.2.1" 
	echo -e "versions zeigt alle verfügbaren versionen"
}

function versioninfo() {
	local info=`echo $DATA | jq '.[] | select(.version == "'$1'")'`
	echo -e "${GRAY}URL: `echo $info|jq '.uri'`"
	echo "SIZE: `echo $info|jq '.size'`"
	echo "SHA1: `echo $info|jq '.sha1'`"
	echo -e "SHA256= `echo $info|jq '.sha256'`${NC}"
}

function versions() {

	local VERSIONS=`echo $DATA |  jq '.[].version'`
	local LATEST=`echo $DATA |  jq '.[0].version'`
	local VERS=(`echo $VERSIONS | tr -d \"`)

	echo "Versionen:"

	for i in "${VERS[@]}"
	do
		echo $i
	done

}

function installFolder() {
	mkdir $1
	cd $1
}

### Config DDEV with PHP version
function installDDEV() {

local swversion=`echo $1 | tr -d .`

if [ "$swversion" -ge "400" ]; then
	local PHP="5.6"
fi
if [ "$swversion" -ge "500" ]; then
	local PHP="7.0"
fi
if [ "$swversion" -ge "510" ]; then
	local PHP="7.1"
fi
if [ "$swversion" -ge "520" ]; then
	local PHP="7.2"
fi

if [ "$swversion" -ge "560" ]; then
	local PHP="7.3"
fi

ddev config --project-type=php --docroot= --webserver-type=apache-fpm --timezone="Europe/Berlin" --php-version=$PHP

curl  `echo $2 | tr -d \"` --output install.zip
unzip -q install.zip && rm install.zip

ddev start

local ddevconfig=`ddev describe -j |jq '.'`
local DDEV_HOSTNAME=`echo $ddevconfig| jq '.raw.hostnames[0]' | tr -d \"`
local DDEV_DOCROOT=""
local DDEV_HTTPURL=`echo $ddevconfig| jq '.raw.httpurl' | tr -d \"`

if [ "$swversion" -ge "540" ]; then
	echo "Automatische Installation..."
	ddev exec "php recovery/install/index.php --no-interaction --quiet --no-skip-import --db-host='db' --db-user='db' --db-password='db' --db-name='db' --shop-locale='de_DE' --shop-host='$DDEV_HOSTNAME' --shop-path='$DDEV_DOCROOT' --shop-name='Demoshop' --shop-email='info@$DDEV_HOSTNAME' --shop-currency='EUR' --admin-username='demo' --admin-password='demo' --admin-email='demo@localhost.localdomain' --admin-name='Demo Admin' --admin-locale='de_DE'"
	echo "Fertig!"
	echo "$DDEV_HTTPURL"	
fi

if [ "$swversion" -lt "540" ]; then
	echo "Manuelle Installation bei Versionen < 5.4.0"
	echo "$DDEV_HTTPURL"
	echo "MySQL Verbindungsdaten:"
	echo "username = db"
	echo "password = db"
	echo "host = db"
	echo "dbname = db"

fi

sed -i "/^#SetEnvIf Host \"dev.shopware.in\" SHOPWARE_ENV=dev/a SetEnvIf Host \"$DDEV_HOSTNAME\" SHOPWARE_ENV=dev" .htaccess

local defaultConfig='$defaultConfig'
cat <<EOF >config_dev.php
<?php
$defaultConfig = require 'config.php'; // config generated by ant build-unit

return [
    'db' => $defaultConfig['db'],

    'front' => [
        'throwExceptions' => true,
        'showException' => true
    ],

    'phpsettings' => [
        'display_errors' => 1
    ],

    'template' => [
        'forceCompile' => true
    ],
];
EOF


}

function install() {
    local VERSIONS=`echo $DATA |  jq '.[].version'`
	local LATEST=`echo $DATA |  jq '.[0].version'`
	local VERS=(`echo $VERSIONS | tr -d \"`)
	local folder="./"

	local value=${VERS[0]}

	if [ ! -z "$1" ]; then
	local value=$1
	fi

	if [[ " ${VERS[@]} " =~ " ${value} " ]]; then
	echo "Okay, Intsalliere Shopware $value"
	local swuri=`echo $DATA | jq '.[] | select(.version == "'$value'")' | jq '.uri' | tr -d \"`
	versioninfo "$value"
	
	echo "Bitte gib den Installationsordner an:"
	read folder;
	
	installFolder "$folder"
	installDDEV "$value" "$swuri";
	
		else
	echo "Leider konnte die gewünschte version $value nicht gefunden werden"
	fi
}

case "$1" in
    install)
        install "$2"
        ;;
    versions)
	versions
	;;
    *)
	help
	;;
esac
